--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Postgres.app)
-- Dumped by pg_dump version 16.4 (Postgres.app)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: _user; Type: TABLE; Schema: public; Owner: stefanoantonetti
--

CREATE TABLE public._user (
    account_locked boolean NOT NULL,
    date_of_birth date,
    enabled boolean NOT NULL,
    created_date timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    last_modified_date timestamp(6) without time zone,
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255)
);


ALTER TABLE public._user OWNER TO stefanoantonetti;

--
-- Name: _user_id_seq; Type: SEQUENCE; Schema: public; Owner: stefanoantonetti
--

ALTER TABLE public._user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public._user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role; Type: TABLE; Schema: public; Owner: stefanoantonetti
--

CREATE TABLE public.role (
    created_date timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    last_modified_date timestamp(6) without time zone,
    name character varying(255)
);


ALTER TABLE public.role OWNER TO stefanoantonetti;

--
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: stefanoantonetti
--

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token; Type: TABLE; Schema: public; Owner: stefanoantonetti
--

CREATE TABLE public.token (
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    validated_at timestamp(6) without time zone,
    token character varying(255) NOT NULL
);


ALTER TABLE public.token OWNER TO stefanoantonetti;

--
-- Name: token_seq; Type: SEQUENCE; Schema: public; Owner: stefanoantonetti
--

CREATE SEQUENCE public.token_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.token_seq OWNER TO stefanoantonetti;

--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: stefanoantonetti
--

CREATE TABLE public.user_roles (
    role_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_roles OWNER TO stefanoantonetti;

--
-- Data for Name: _user; Type: TABLE DATA; Schema: public; Owner: stefanoantonetti
--

COPY public._user (account_locked, date_of_birth, enabled, created_date, id, last_modified_date, email, first_name, last_name, password) FROM stdin;
f	\N	f	2024-09-25 10:52:52.063451	1	\N	pantonetti@libero.it	Paolo	Antonetti	$2a$10$/UE.eH5PWccIff2RwmxF0OHwACjnJvLJXO0Gs7l4MuMjURLTnafhK
f	\N	t	2024-09-25 11:09:28.688318	2	\N	220563@studenti.unimore.it	Stefano	Antonetti	$2a$10$oE22Hdk9IoNXYGpwV.JsVelU7YCKIF3BhVlp5oCFccDnrB/Z78V4W
f	\N	f	2024-09-25 15:08:46.238303	4	\N	anton.steve96@libero.it	Stefano	Antonetti	$2a$10$jXE4789XtbrSGX7bTAEzuu8pLk.DvFcHbpi2Wrjb56GBgtx5huUkm
\.


--
-- Data for Name: role; Type: TABLE DATA; Schema: public; Owner: stefanoantonetti
--

COPY public.role (created_date, id, last_modified_date, name) FROM stdin;
2024-09-25 10:50:36.458052	1	\N	USER
\.


--
-- Data for Name: token; Type: TABLE DATA; Schema: public; Owner: stefanoantonetti
--

COPY public.token (created_at, expires_at, id, user_id, validated_at, token) FROM stdin;
2024-09-25 10:52:52.079404	2024-09-26 10:52:52.079406	1	1	\N	117420
2024-09-25 11:09:28.707499	2024-09-26 11:09:28.707501	2	2	2024-09-25 14:55:18.090629	431535
2024-09-25 15:08:46.253065	2024-09-26 15:08:46.253067	3	4	\N	632334
\.


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: stefanoantonetti
--

COPY public.user_roles (role_id, user_id) FROM stdin;
1	1
1	2
1	4
\.


--
-- Name: _user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: stefanoantonetti
--

SELECT pg_catalog.setval('public._user_id_seq', 4, true);


--
-- Name: role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: stefanoantonetti
--

SELECT pg_catalog.setval('public.role_id_seq', 1, true);


--
-- Name: token_seq; Type: SEQUENCE SET; Schema: public; Owner: stefanoantonetti
--

SELECT pg_catalog.setval('public.token_seq', 51, true);


--
-- Name: _user _user_email_key; Type: CONSTRAINT; Schema: public; Owner: stefanoantonetti
--

ALTER TABLE ONLY public._user
    ADD CONSTRAINT _user_email_key UNIQUE (email);


--
-- Name: _user _user_pkey; Type: CONSTRAINT; Schema: public; Owner: stefanoantonetti
--

ALTER TABLE ONLY public._user
    ADD CONSTRAINT _user_pkey PRIMARY KEY (id);


--
-- Name: role role_name_key; Type: CONSTRAINT; Schema: public; Owner: stefanoantonetti
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_name_key UNIQUE (name);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: stefanoantonetti
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- Name: token token_pkey; Type: CONSTRAINT; Schema: public; Owner: stefanoantonetti
--

ALTER TABLE ONLY public.token
    ADD CONSTRAINT token_pkey PRIMARY KEY (id);


--
-- Name: token token_token_key; Type: CONSTRAINT; Schema: public; Owner: stefanoantonetti
--

ALTER TABLE ONLY public.token
    ADD CONSTRAINT token_token_key UNIQUE (token);


--
-- Name: user_roles fkcbsnrgq3e9qe6kuxq7wx6vlfm; Type: FK CONSTRAINT; Schema: public; Owner: stefanoantonetti
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkcbsnrgq3e9qe6kuxq7wx6vlfm FOREIGN KEY (user_id) REFERENCES public._user(id);


--
-- Name: token fkiblu4cjwvyntq3ugo31klp1c6; Type: FK CONSTRAINT; Schema: public; Owner: stefanoantonetti
--

ALTER TABLE ONLY public.token
    ADD CONSTRAINT fkiblu4cjwvyntq3ugo31klp1c6 FOREIGN KEY (user_id) REFERENCES public._user(id);


--
-- Name: user_roles fkrhfovtciq1l558cw6udg0h0d3; Type: FK CONSTRAINT; Schema: public; Owner: stefanoantonetti
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkrhfovtciq1l558cw6udg0h0d3 FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- PostgreSQL database dump complete
--

