spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
    database: ${SPRING_JPA_DATABASE:postgresql}
    open-in-view: ${SPRING_JPA_OPEN_IN_VIEW:false}
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
  thymeleaf:
    check-template-location: ${SPRING_THYMELEAF_CHECK_TEMPLATE_LOCATION:false}
  jmx:
    enabled: ${SPRING_JMX_ENABLED:true}

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}
          connection-timeout: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT:5000}
          timeout: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT:5000}
          write-timeout: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT:5000}
        protocol: ${SPRING_MAIL_PROTOCOL:smtp}

application:
  security:
    jwt:
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY}
      expiration: ${APPLICATION_SECURITY_JWT_EXPIRATION}
  mailing:
    frontend:
      activation-url: ${APPLICATION_MAILING_FRONTEND_ACTIVATION_URL}

  file:
    upload:
      photos-output-path: ${UPLOAD_PHOTOS_OUTPUT_PATH}

#Tomcat
server:
  tomcat:
    threads:
      max: ${TOMCAT_THREADS_MAX:200}
      min-spare: ${TOMCAT_THREADS_MIN_SPARE:10}
    connection-timeout: ${TOMCAT_CONNECTION_TIMEOUT:20000}
    max-connections: ${TOMCAT_MAX_CONNECTIONS:100}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/api/v1/}


#Logging
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:DEBUG}
    org.springframework: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK:DEBUG}
    com.antonsteve96.ngrx: ${LOGGING_LEVEL_COM_MYCOMPANY_BOOK:DEBUG}
    org.springframework.web: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB:INFO}
    org.hibernate.SQL: ${LOGGING_LEVEL_ORG_HIBERNATE_SQL:DEBUG}
    org.hibernate.type: ${LOGGING_LEVEL_ORG_HIBERNATE_TYPE:TRACE}
  file:
    name: ${LOGGING_FILE_NAME:logs/spring-boot-application.log}
