spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  servlet:
    multipart:
      max-file-size: 50MB
  datasource:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    open-in-view: true


springdoc:
  default-produces-media-type: application/json


server:
  tomcat:
    threads:
      max: ${TOMCAT_THREADS_MAX:200}
      min-spare: ${TOMCAT_THREADS_MIN_SPARE:10}
    connection-timeout: ${TOMCAT_CONNECTION_TIMEOUT:20000}
    max-connections: ${TOMCAT_MAX_CONNECTIONS:100}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/api/v1/}

